[package]
name = "badfs-playground"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
anyhow = "1.0.42"
log = "0.4"
env_logger = "0.9"

[build-dependencies]
cc = "1.0"