name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependency
      run: sudo apt install -y libopenmpi-dev
    - name: Build
      run: cd ior && ./bootstrap && ./configure CFLAGS="-g -O0 -fPIC" && sudo make install && LD_LIBRARY_PATH=/usr/local/lib cargo build --verbose

