name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependency
      run: sudo apt install -y libopenmpi-dev
    - name: Build
      run: LD_LIBRARY_PATH=/usr/local/lib cargo build --verbose
    - name: Run tests
      run: LD_LIBRARY_PATH=/usr/local/lib cargo test --verbose
